name = "kino-rooms"
main = "src/worker.js"
compatibility_date = "2024-11-06"

[durable_objects]
bindings = [{ name = "ROOM", class_name = "Room" }]

[[migrations]]
tag = "v2"
new_classes = ["Room"]

[observability]
enabled = true
head_sampling_rate = 1
